Данные храняться в типе данных ndarray - n-мерный массив. У него есть размер(shape), тип элементов(dtype) и strides.

Вот базовые операции с array в numpy

In [11]:
import numpy as np
a = np.array([[1,2,3],
                [4,5,6]], dtype=np.float32)

print(a.shape)
print(a.ndim)
print(a.dtype)
print(a.itemsize)
print(a.size)

b = a.reshape(3,2)
print(b)
c = a.ravel()
print(c, c.shape)
d = a.flatten()
print(d)
print(a)

(2, 3)
2
float32
4
6
[[1. 2.]
 [3. 4.]
 [5. 6.]]
[1. 2. 3. 4. 5. 6.] (6,)
[1. 2. 3. 4. 5. 6.]
[[1. 2. 3.]
 [4. 5. 6.]]


In [32]:
X = np.arange(20, dtype=np.float32).reshape(4,5)
#print(X)
print(X[::2, 1:], X)

print()
print(X)
X[X<5]=0
print(X)
np.where(X> 10, X, 0)

[[ 1.  2.  3.  4.]
 [11. 12. 13. 14.]] [[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]
 [15. 16. 17. 18. 19.]]

[[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]
 [15. 16. 17. 18. 19.]]
[[ 0.  0.  0.  0.  0.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]
 [15. 16. 17. 18. 19.]]


array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.]], dtype=float32)

In [37]:
print(X[1:4][::2])
med = np.median(X, axis=0, keepdims=True)
np.where(X>med, X, 0)

Y = X[[3,0,3,2], :]
Y = Y[:, [4,1]]
print(Y)


print(
X[..., 1::2])


[[ 5.  6.  7.  8.  9.]
 [15. 16. 17. 18. 19.]]
[[19. 16.]
 [ 0.  0.]
 [19. 16.]
 [14. 11.]]
[[ 0.  0.]
 [ 6.  8.]
 [11. 13.]
 [16. 18.]]


Broadcasting - это способность numpy приводить разные массивы к растянутому размера для выполнения поэлементных операций. 

In [39]:
mu = X.mean(axis=0, keepdims=True)
su = X.std(axis=0, keepdims=True)
Z = (X - mu) / (su - 1e-12)
print(Z)

norms = np.linalg.norm(X, axis=1, keepdims=True)


[[-1.3416408  -1.3907841  -1.4320031  -1.466746   -1.496188  ]
 [-0.4472136  -0.37930477 -0.3182229  -0.2632621  -0.21374115]
 [ 0.4472136   0.46359473  0.47733438  0.48891532  0.49872938]
 [ 1.3416408   1.3064942   1.2728916   1.2410927   1.2111999 ]]
